SYSTEST-9245-Log user IDs in an array in MF logs instead of multiple lines
rdkcentral/mock-firebolt pull request #106
Opened 2023-02-02 08:07 UTC by Nandana-NNR

2023-02-05 00:04 UTC, kschrief commented on server/src/index.mjs
> +stateManagement.addUser('123'); userManagement.addUser('123');
Can you remove these three lines? With the appId changes adding 123, 456, 789 is preventing 123~A, 456~A, and 789~A from being added which are commonly used userIds.

2023-02-05 00:07 UTC, kschrief requested changes

2023-02-05 00:07 UTC, kschrief commented on server/src/routes/api/user.mjs
> +import { logger } from '../../../src/logger.mjs';
You don't have to go all the way up to root. You can just ../../logger.mjs

2023-02-05 00:07 UTC, kschrief commented on server/src/stateManagement.mjs
> +  defaultUserArray,
We can just call userManagement.getUsers(). We don't need to keep track of "default" users

2023-02-05 00:07 UTC, kschrief commented on server/src/routes/api/user.mjs
> +      logger.info(`Adding user ${userId}`);
Can we say "Added" instead of "Adding"?

2023-02-07 16:05 UTC, dhillomk approved these changes

2023-02-07 17:40 UTC, merged