SYSTEST-9447-Create config associations
rdkcentral/mock-firebolt pull request #140
Opened 2023-08-17 11:52 UTC by Nandana-NNR

2023-08-17 17:08 UTC, kschrief requested changes

2023-08-17 17:08 UTC, kschrief commented on server/src/config.mjs
> +      logger.warn(`WARNING: There is an unused config ${newObj.name}. Refer ${newObj.readme} for more info `);
We need to check if `newObj.readme` is present or not. If it's null/undefined the warning log will be improper.

2023-08-17 17:08 UTC, kschrief commented on server/src/config.mjs
> +      logger.warn(`WARNING: The config ${changedObj.oldName} has been renamed to ${changedObj.newName}. Refer ${changedObj.readme} for more info `);
We need to check if `newObj.readme` is present or not. If it's null/undefined the warning log will be improper.

2023-08-17 17:08 UTC, kschrief commented on server/src/changedConfigs.json
> +{
Can we make a change to this based off of Mike's comments?

Let's change to the below format:

`[
  {
    "type": "new",
    "name": "xyz",
    "readme": "readme.md"
  },
  {
    "type": "changed",
    "oldName": "abc",
    "newName": "xyz",
    "readme": "readme.md"
  }
]`

Sorry for the last-minute ask.

2023-08-22 20:14 UTC, kschrief approved these changes

2023-08-23 13:30 UTC, michaelcfine approved these changes
Looks good. A few minor comments.

2023-08-23 13:30 UTC, michaelcfine commented on server/src/config.mjs
> +      if (newNameToCheck && !searchJSONforParam(loadedConfig, newNameToCheck)) {
JSON is a string serialization format... so technically, I think you're really 'just' searching an object for a param. I don't think it's critical, but you could/eventually should rename this function something like 'searchObjectForParam' or perhaps better 'searchObjectForKey'. Minor, but sometimes naming subtleties can help/hurt.

2023-08-24 12:59 UTC, kschrief approved these changes

2023-08-28 17:01 UTC, merged