FIRECERT-1846-POC to add ability to check if an active userid is connected or not from yaml file for hot/cold launch scenarios
rdkcentral/mock-firebolt pull request #150
Opened 2024-02-13 10:35 UTC by Nandana-NNR

Ticket - https://ccp.sys.comcast.net/browse/FIRECERT-1846

2024-02-13 14:07 UTC, Nandana-NNR reviewed
As per current usecase for discovery launch scenarios, only the ctx object inside 
stateManagement->handleDynamicResponseValues needs to be updated as this is the only updated function that gets triggered when override is set. But to maintain consistency and considering the possibility of future usecases, I have updated the ctx objects defined across all other files to include the new function. Let me know if that's ok or do we need to cover only ctx object in handleDynamicResponseValues for now
cc @kschrief

2024-02-20 15:28 UTC, kschrief requested changes

2024-02-20 15:28 UTC, kschrief commented on server/src/userManagement.mjs
> +    if (wsArray) {
Let's check for a non-empty array as well.

2024-02-20 15:28 UTC, kschrief commented on server/src/userManagement.mjs
> +      user2ws.delete(''+userId);
I think we need to do this a little differently. This line deletes the entire Array of WS objects for the user. If we run this when the user has more than one connection the others will be put in a weird state.

We should go through the array and delete _only_ the current ws object from the array.

2024-11-08 10:35 UTC, closed without merging