Use ipaddress as userId if userId is missing
rdkcentral/mock-firebolt pull request #39
Opened 2022-07-14 12:25 UTC by naimish15

2022-07-14 12:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/mock-firebolt?pullRequest=39) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/mock-firebolt?pullRequest=39) before we can accept your contribution.<br/><hr/>**Naimish Patel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/mock-firebolt?pullRequest=39) it.</sub>

2022-07-15 14:52 UTC, kschrief requested changes

2022-07-15 14:52 UTC, kschrief commented on server/src/index.mjs
> +    userId = ipAddresses.slice(ipAddresses.lastIndexOf(":") + 1);
This looks like it covers IPv6 addresses only. What about IPv4?

We should be removing all "." in IPv4 addresses and all ":" in IPv6

2022-07-18 17:07 UTC, kschrief approved these changes

2022-07-18 17:42 UTC, michaelcfine commented
I don't think the logic added is quite right, but even if it is, it isn't sufficient... user ids have to 'formally' exist before they can be used (see isKnownUser), so at the very least, you'll need to also add the user with the given userId (IP#). See https://github.com/rdkcentral/mock-firebolt/blob/main/server/src/index.mjs#L63. Note that you have to add the user and then also set up default state for that user (hence the two separate calls).

2022-07-19 10:32 UTC, closed without merging

2022-07-19 10:33 UTC, naimish15 commented
I was facing some issues in this PR so I will create new PR