implemented changes for method & event Triggers refactoring
rdkcentral/mock-firebolt pull request #45
Opened 2022-07-26 12:31 UTC by warbhe-amit

Implemented changes for method & event Triggers refactoring

2022-07-26 15:00 UTC, michaelcfine requested changes
This seems to be code to implement the 'broadcastEvent' feature, not really refactoring triggers, but that's okay. This looks pretty good, but I think in all five cases where ctx objects are being created, you're not calling the right function with the right signature for sendEvent and sendBroadcastEvent. See my comments. In all cases, ctx.sendEvent should call events.sendEvent(<no boolean param>) and ctx.sendBroadcastEvent should call events.sendBroadcastEvent(<no boolean param>). The refactoring to coreSendEvent should have left the signatures for those methods NOT having a boolean param; only coreSendEvent has the boolean and it is private; so calling code should not pass it.

Also... See my comment about refactoring the events.coreSendEvent function when it comes to sending messages over the sockets. Please refactor so that first you get a list of sockets (different logic depending on broadcast or not) and then loop through the list (which can now be 100% the same code).

Also... please test thoroughly. I don't see how this code would have run properly with the invocations not matching the signatures. Thanks.

2022-07-27 12:05 UTC, warbhe-amit commented on server/src/events.mjs
> +    console.log('user', user);
Done

2022-07-27 12:05 UTC, warbhe-amit commented on server/src/events.mjs
> +function isRegisteredEventListenerInGroup(userId, method) {
Done

2022-07-27 12:08 UTC, warbhe-amit commented on server/src/events.mjs
> +                sendEvent(false, ws, userId, method, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-27 12:09 UTC, warbhe-amit commented on server/src/events.mjs
> +                events.sendEvent(true, ws, userId, onMethod, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-27 12:09 UTC, warbhe-amit commented on server/src/events.mjs
> +                sendEvent(false, ws, method, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-27 12:10 UTC, warbhe-amit commented on server/src/messageHandler.mjs
> +            events.sendEvent(false, ws, userId, onMethod, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-27 12:10 UTC, warbhe-amit commented on server/src/messageHandler.mjs
> +            events.sendEvent(true, ws, userId, onMethod, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-27 12:10 UTC, warbhe-amit commented on server/src/messageHandler.mjs
> +            events.sendEvent(true, ws, userId, onMethod, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-27 12:11 UTC, warbhe-amit commented on server/src/stateManagement.mjs
> +          events.sendEvent(true, ws, userId, onMethod, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-27 12:11 UTC, warbhe-amit commented on server/src/stateManagement.mjs
> +          events.sendEvent(false, ws, userId, onMethod, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-27 12:12 UTC, warbhe-amit commented on server/src/events.mjs
> +                events.sendEvent(true, ws, userId, onMethod, result, msg, fSuccess, fErr, fFatalErr);
Done

2022-07-28 10:47 UTC, warbhe-amit commented on server/src/events.mjs
> +      let id;
done

2022-08-03 14:12 UTC, michaelcfine approved these changes
👍 Looks good.

2022-08-03 14:29 UTC, merged