MF Scope - Implementation
rdkcentral/mock-firebolt pull request #73
Opened 2022-09-23 11:50 UTC by sourabhk2399

MF Scope - Implementation

2022-09-23 15:15 UTC, kschrief requested changes

2022-09-23 15:15 UTC, kschrief commented on server/src/stateManagement.mjs
>  function getState(userId) {
So we should be returning a combination of the global/group/user state, not just one of them.

Ex: getState('123~abc') should:
* Load the global state
* Load the state for group "~123" if it exists. All fields in this state should be combined with the global state. Any conflicts should have the group state chosen
* Load the state for userId 'abc~123'. All fields in this state should be combined with the newly created group+global state. Any conflicts should have the userId state chosen

This new state is the one that should be returned

2022-09-23 15:15 UTC, kschrief commented on server/src/stateManagement.mjs
> +function updateState(userId, newState, scope = "") {
We do not need to add a scope variable here. The userId used will provide us our scope. This is why I'd mentioned that the update functionalities do not need to be updated.

Someone wishing to update the ~abc or "global" scope would just set the userId to "~abc" or "global" when calling the API/CLI. That would then end up here as the userId

2022-09-30 13:07 UTC, kschrief commented on server/src/stateManagement.mjs
> +function updateState(userId, newState, scope = "") {
After conversation there was a mis-understanding on my part. Resolving conversation.

2022-10-04 15:51 UTC, kschrief approved these changes

2022-10-07 15:31 UTC, michaelcfine approved these changes
LGTM

2022-10-10 17:53 UTC, kschrief approved these changes

2022-10-11 08:37 UTC, sourabhk2399 commented on cli/examples/closed-captions-settings.yaml
> +        console.log("### value of ctx inside closedcaptions.enabled of yaml",ctx)
I'll remove this next commit.

2022-10-11 08:37 UTC, merged